### ISSUE TITLE
--- ERROR --- Couldn't copy file

### ISSUE THREAD

**Issue by cpetito** [Schallbert/DFplayer_AutoStructureFromPlaylist#7] opened 2023-06-07 14:50 UTC
This is a very useful and time saving application for me.  Thank you!

As an FI, it wasn't running on Windows 10, Python 3.10.0.  It would exit with the error "--- ERROR --- Couldn't copy file ..." 

I'm not a python expert, but I found that I needed to change line 33 in AutoStructureFilesForDFplayer.py

from: if playlist_line.find(M3UFILEMARKER) :
to:     if playlist_line.find(M3UFILEMARKER) == 0:

**Comment by Schallbert** [comment] 2023-06-14 19:48
Hey @cpetito,

sorry for the late reply. Can you please give more details about under which circumstances that error occurred? I do require:
- the original playlist line that the error message printed out
- the targeted path that is also printed along with that message
- the playlist you tried to run the script on
What you did to fix actually changes the logic so that the script will behave incorrectly if there is no `file:///` marker in the source ´.m3u´.

Likely the true culprit is a special character in one of your mp3 titles or a wrong filter for the file marker that the script cannot handle, but I'd have to know which one it is to provide a permanent fix.

Thanks and regards
**Schallbert**

**Comment by cpetito** [comment] 2023-07-16 21:00
Sorry, it took awhile to get back around to this.  Here is the output for three runs: the initial creation of the SDcardFolders, the creation of the destination folder and finally a run with source and destination folders created. 

**`C:\Users\cpetito\Apps\DFplayer_AutoStructureFromPlaylist>AutoStructureFilesForDFplayer.py
Starting Conversion application for structuring files for DFplayerMini.
This script analyzes .m3u playlists and restructures their contents to a format readable by the DFmini mp3 module.

Hooked to current working directory: C:\Users\cpetito\Apps\DFplayer_AutoStructureFromPlaylist
Did not find folder containing SD card MP3 folders.
    Trying to create folder SDcardFolders for you.
    You will find the files to transfer to your DFplayerMini's SD card there
Did not find folder containing m3u playlists. Trying to create one for you...
            SUCCESS: Created folder PlayListsM3U
            Please move your playlists here and run the application again.
Press Return to quit...


C:\Users\cpetito\Apps\DFplayer_AutoStructureFromPlaylist>AutoStructureFilesForDFplayer.py
Starting Conversion application for structuring files for DFplayerMini.
This script analyzes .m3u playlists and restructures their contents to a format readable by the DFmini mp3 module.

Hooked to current working directory: C:\Users\cpetito\Apps\DFplayer_AutoStructureFromPlaylist
SDcard MP3 folders found. Will modify contents based on playlist input.
    Existing folders: []

Folder with playlists found. Trying to create DFplayer folders and files for: ['01_Electric Blues.m3u']
--- ERROR --- Couldn't copy file
file:///c:/users/cpetito/music/amazon/electric blues/01 - mojo boogie.mp3 to:
C:\Users\cpetito\Apps\DFplayer_AutoStructureFromPlaylist\SDcardFolders\01
Aborting.
Press Return to quit...


C:\Users\cpetito\Apps\DFplayer_AutoStructureFromPlaylist>AutoStructureFilesForDFplayer.py
Starting Conversion application for structuring files for DFplayerMini.
This script analyzes .m3u playlists and restructures their contents to a format readable by the DFmini mp3 module.

Hooked to current working directory: C:\Users\cpetito\Apps\DFplayer_AutoStructureFromPlaylist
SDcard MP3 folders found. Will modify contents based on playlist input.
    Existing folders: ['01']

--- ERROR --- PlayListM3U folder contains unsupported file types:  01_Electric Blues.txt
    make sure you only place .m3u files here! Aborting.
Press Return to quit...`**

If I change line 33 to: `if playlist_line.find(M3UFILEMARKER) == 0:`  it works without error.

Note, I had to rename the .m3u file to .txt to attach.

[01_Electric Blues.txt](https://github.com/Schallbert/DFplayer_AutoStructureFromPlaylist/files/12065047/01_Electric.Blues.txt)

I hope this helps and thank you for the app!

**Comment by Schallbert** [comment] 2023-07-25 19:01
Hey @cpetito, thanks for the detailed reply.

I just ran your file through on my machine (obviously without the source files this cannot succeed), but what struck me was that in your run, the marker `file:///` in the playlist was still shown in the output although it should have been found and removed by the logic you mentioned in line33. 

I was using an older python version at the time I wrote that thing but I cannot imagine that that's the root cause.
Can you give it another try with the following statement, please:

`if playlist_line.find(M3UFILEMARKER) > -1`

This check is more inclusive and would also detect if the 'file' marker wasn't at line beginning but later and thus is more robust against messed-up playlist file design.

If this works for you, too, I'll create a new minor release (and make other statements more expessive as well to mitigate future issues that are similar)

Thanks and regards
_Schallbert_

**Comment by Schallbert** [comment] 2023-07-26 19:40
I wrote a fix that takes a possibly changed find() interpretation into account. You can find it [here](https://github.com/Schallbert/DFplayer_AutoStructureFromPlaylist/suites/14592400971/artifacts/826754735). 
Maybe you can try it out and tell me whether this works for you. It passes my integration tests, at least.

Thank you very much for helping me improve the software.
_Schallbert_

**Comment by Schallbert** [comment] 2023-10-29 14:40
Missing feedback, closing as completed (passes integration tests).

**Closed as completed by Schallbert** 2023-10-29 14:40 UTC
